#!/bin/bash
set -euo pipefail

# Only run in remote (Claude Code on the web) environments
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

# Install gh CLI if not present
if ! command -v gh &>/dev/null; then
  mkdir -p /tmp/gh-install && cd /tmp/gh-install
  curl -sL https://github.com/cli/cli/releases/download/v2.65.0/gh_2.65.0_linux_amd64.tar.gz -o gh.tar.gz
  tar xzf gh.tar.gz
  cp gh_2.65.0_linux_amd64/bin/gh /usr/local/bin/gh 2>/dev/null \
    || { mkdir -p "$HOME/.local/bin" && cp gh_2.65.0_linux_amd64/bin/gh "$HOME/.local/bin/gh" && echo "export PATH=\"\$HOME/.local/bin:\$PATH\"" >> "$CLAUDE_ENV_FILE"; }
  rm -rf /tmp/gh-install
fi

# Set GH_REPO so gh works through the git proxy (can't infer repo from proxy URL)
# Parse owner/repo from the git remote
GH_REPO_DETECTED=$(git -C "$CLAUDE_PROJECT_DIR" remote get-url origin 2>/dev/null \
  | sed -n 's|.*/git/\(.*\)$|\1|p' \
  | sed 's/\.git$//')
if [ -n "${GH_REPO_DETECTED:-}" ]; then
  echo "export GH_REPO=\"${GH_REPO_DETECTED}\"" >> "$CLAUDE_ENV_FILE"
  export GH_REPO="$GH_REPO_DETECTED"
fi

# Install Supabase CLI if not present
if ! command -v supabase &>/dev/null; then
  npm install -g supabase
fi

# Install Vercel CLI if not present
if ! command -v vercel &>/dev/null; then
  npm install -g vercel
fi

# Install Playwright browsers if not present
if ! npx playwright install --dry-run chromium &>/dev/null 2>&1; then
  npx playwright install --with-deps chromium
fi

# Install Node.js dependencies for the web app
cd "$CLAUDE_PROJECT_DIR/web"
npm install

# Start local Supabase (if not already running)
# NOTE: Edge Runtime is excluded (-x edge-runtime) because:
#   - The Claude Code web container has no external DNS, so the Deno-based
#     edge runtime can't fetch dependencies from deno.land / jsr.io.
#   - Edge Functions are NOT used in v1 — the WhatsApp webhook runs as a
#     Vercel API route, so excluding edge-runtime has zero impact on tests.
cd "$CLAUDE_PROJECT_DIR"
if ! supabase status &>/dev/null 2>&1; then
  supabase start -x edge-runtime
fi

# Generate .env.local with Supabase connection details (for integration/E2E tests)
STATUS_JSON=$(supabase status -o json 2>/dev/null || true)
if [ -n "$STATUS_JSON" ]; then
  SUPABASE_URL=$(echo "$STATUS_JSON" | jq -r '.API_URL // "http://127.0.0.1:54321"')
  SUPABASE_ANON_KEY=$(echo "$STATUS_JSON" | jq -r '.ANON_KEY')
  SUPABASE_SECRET_KEY=$(echo "$STATUS_JSON" | jq -r '.SERVICE_ROLE_KEY')
  DB_URL=$(echo "$STATUS_JSON" | jq -r '.DB_URL')

  cat > "$CLAUDE_PROJECT_DIR/web/.env.local" <<EOF
# Auto-generated by .claude/hooks/session-start.sh
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$SUPABASE_ANON_KEY
SUPABASE_SECRET_KEY=$SUPABASE_SECRET_KEY
DATABASE_URL=$DB_URL
EOF

  # Create storage bucket (idempotent)
  curl -sf -X POST "$SUPABASE_URL/storage/v1/bucket" \
    -H "Authorization: Bearer $SUPABASE_SECRET_KEY" \
    -H "Content-Type: application/json" \
    -d '{"id":"media","name":"media","public":false}' \
    2>/dev/null || true
fi
