#!/bin/bash
# Local development environment setup using Supabase CLI
# This script starts a full local Supabase environment (Postgres + Storage + Edge Functions)

set -e

echo "================================================"
echo "  Starting Supabase Local Development Environment"
echo "================================================"
echo ""

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
    echo "Error: Supabase CLI not found. Install it first:"
    echo "  brew install supabase/tap/supabase (macOS)"
    echo "  https://supabase.com/docs/guides/cli/getting-started"
    exit 1
fi

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo "Error: Node.js not found. Install Node.js 20+:"
    echo "  https://nodejs.org/"
    exit 1
fi

# Check if web dependencies are installed
if [ ! -d "web/node_modules" ]; then
    echo "Installing web dependencies..."
    cd web && npm install && cd ..
fi

# Start Supabase (Postgres + Storage + Edge Functions + Studio)
echo "Starting Supabase services..."
supabase start

echo ""
echo "Extracting environment variables..."

# Get Supabase connection details (keys are UPPERCASE in JSON)
STATUS_JSON=$(supabase status -o json 2>/dev/null)

if [ -n "$STATUS_JSON" ]; then
    SUPABASE_URL=$(echo "$STATUS_JSON" | jq -r '.API_URL // "http://localhost:54321"')
    SUPABASE_ANON_KEY=$(echo "$STATUS_JSON" | jq -r '.ANON_KEY')
    SUPABASE_SECRET_KEY=$(echo "$STATUS_JSON" | jq -r '.SERVICE_ROLE_KEY')
    DB_URL=$(echo "$STATUS_JSON" | jq -r '.DB_URL')
    STORAGE_S3_URL=$(echo "$STATUS_JSON" | jq -r '.STORAGE_S3_URL // .API_URL + "/storage/v1/s3"')

    # Extract S3 credentials from table output (not in JSON)
    STATUS_TABLE=$(supabase status 2>/dev/null)
    AWS_ACCESS_KEY_ID=$(echo "$STATUS_TABLE" | grep "Access Key" | awk -F '│' '{print $3}' | tr -d ' ')
    AWS_SECRET_ACCESS_KEY=$(echo "$STATUS_TABLE" | grep "Secret Key" | awk -F '│' '{print $3}' | tr -d ' ')
else
    echo "Warning: Could not get supabase status, using defaults"
    SUPABASE_URL="http://localhost:54321"
    SUPABASE_ANON_KEY=""
    SUPABASE_SECRET_KEY=""
    DB_URL=""
    STORAGE_S3_URL="http://localhost:54321/storage/v1/s3"
    AWS_ACCESS_KEY_ID="local-access-key"
    AWS_SECRET_ACCESS_KEY="local-secret-key"
fi

STORAGE_ENDPOINT="$SUPABASE_URL/storage/v1"

# Create storage bucket for media
echo ""
echo "Creating storage bucket 'media'..."
curl -sf -X POST "$STORAGE_ENDPOINT/bucket" \
  -H "Authorization: Bearer $SUPABASE_SECRET_KEY" \
  -H "Content-Type: application/json" \
  -d '{"id":"media","name":"media","public":false}' \
  2>/dev/null || echo "  (Bucket may already exist)"

# Write environment file
ENV_FILE=".env.local"
cat > "$ENV_FILE" << EOF
# Supabase Local Development Environment
# Generated by scripts/local-dev.sh

# Backend API (CLI + server-side)
SMGR_API_URL=$SUPABASE_URL
SMGR_API_KEY=$SUPABASE_ANON_KEY
SUPABASE_SECRET_KEY=$SUPABASE_SECRET_KEY

# Next.js frontend (browser-side, required by Next.js convention)
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$SUPABASE_ANON_KEY

# smgr CLI configuration
SMGR_S3_ENDPOINT=$STORAGE_S3_URL
SMGR_S3_BUCKET=media
SMGR_S3_REGION=local
SMGR_DEVICE_ID=local-dev
SMGR_AUTO_ENRICH=false

# For S3 compatibility
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
AWS_ENDPOINT_URL_S3=$STORAGE_S3_URL

# Database (for direct connections if needed)
DATABASE_URL=$DB_URL

# Enrichment (set your real API key for testing)
SMGR_ENRICHMENT_PROVIDER=anthropic
# ANTHROPIC_API_KEY=sk-ant-...  # Uncomment and add your key

# Bot configuration (optional, for local testing)
# TWILIO_ACCOUNT_SID=...
# TWILIO_AUTH_TOKEN=...
# TWILIO_WHATSAPP_FROM=whatsapp:+...
EOF

echo ""
echo "================================================"
echo "  LOCAL ENVIRONMENT READY"
echo "================================================"
echo ""
echo "Supabase Studio:  http://localhost:54323"
echo "API URL:          $SUPABASE_URL"
echo "Storage API:      $STORAGE_ENDPOINT"
echo "Database:         $DB_URL"
echo ""
echo "Environment variables saved to: $ENV_FILE"
echo "Load them with: source $ENV_FILE"
echo ""
echo "------------------------------------------------"
echo "  Quick Start Commands"
echo "------------------------------------------------"
echo ""
echo "1. Load environment:"
echo "   source $ENV_FILE"
echo ""
echo "2. Check status:"
echo "   cd web && npm run smgr stats"
echo ""
echo "3. Watch for S3 changes:"
echo "   cd web && npm run smgr watch"
echo ""
echo "4. Run unit tests:"
echo "   cd web && npm test"
echo ""
echo "5. Run integration tests:"
echo "   ./tests/integration_test.sh"
echo ""
echo "------------------------------------------------"
echo "To stop Supabase: supabase stop"
echo "To view logs:     supabase logs"
echo ""
